include:
  - path: ./docker-compose.base.yml
services:
  convert-tool:
    build: convert-tool
    image: labelstudio-convert-tool
    restart: unless-stopped
    volumes:
      - .docker/mydata:/label-studio/data:rw
    environment:
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}